{
 "title": "Hammerspace User Capacity Utilization Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "USERSELECT", "label": "Select User", "query": { "query": "fileshare_user_capacity" } },
   { "name": "Share", "label": "Select Share", "query": { "query": "fileshare_user_capacity_all" } }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 49, "w": 1, "x": 0, "y": 0 }, "options": { "content": "\n\n" } },
  {
   "title": "Hammerspace User Capacity Dashboard",
   "type": "text",
   "gridPos": { "h": 1, "w": 22, "x": 1, "y": 0 },
   "options": { "content": "\n\n" }
  },
  { "type": "text", "gridPos": { "h": 49, "w": 1, "x": 23, "y": 0 }, "options": { "content": "\n\n" } },
  { "title": "User Capacity Reports", "type": "text", "gridPos": { "h": 1, "w": 11, "x": 1, "y": 1 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 48, "w": 1, "x": 12, "y": 1 }, "options": { "content": "\n\n" } },
  { "title": "User File Count Reports", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 13, "y": 1 }, "options": { "content": "\n\n" } },
  {
   "title": "System Total Consumed User Capacity - All Shares",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 1, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "fileshare_capacity_total{Size=\"MBYTES\"}",
     "legendFormat": "Total User Capacity"
    },
    { "expr": "fileshare_capacity_aged_total", "legendFormat": "     Inactive Data  ( > 6MO )" }
   ]
  },
  {
   "title": "System Total User File Count - All Shares",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "fileshare_count_total", "legendFormat": "Total File Count" },
    {
     "expr": "fileshare_count_aged_total",
     "legendFormat": "  Inactive File Count ( > 6MO )"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 11, "x": 1, "y": 9 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 1, "w": 10, "x": 13, "y": 9 }, "options": { "content": "\n\n" } },
  {
   "title": "User Capacity Total - All Shares",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "fileshare_user_capacity{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}"
    }
   ]
  },
  {
   "title": "User File Count Total - All Shares",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "fileshare_user_count{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 11, "x": 1, "y": 19 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 1, "w": 10, "x": 13, "y": 19 }, "options": { "content": "\n\n" } },
  {
   "title": "User Capacity Total - All Shares - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "fileshare_user_capacity{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}"
    }
   ]
  },
  {
   "title": "User File Count Total - All Shares - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fileshare_user_count{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 11, "x": 1, "y": 29 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 1, "w": 10, "x": 13, "y": 29 }, "options": { "content": "\n\n" } },
  {
   "title": "User Capacity - Individual Shares",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "fileshare_user_capacity_all{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}  - {{Share}}"
    }
   ]
  },
  {
   "title": "User File Count - Individual Shares",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fileshare_user_count_all{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}  -  {{Share}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 11, "x": 1, "y": 38 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 1, "w": 10, "x": 13, "y": 38 }, "options": { "content": "\n\n" } },
  {
   "title": "User Capacity - Individual Shares - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "fileshare_user_capacity_all{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}  -  {{Share}}"
    }
   ]
  },
  {
   "title": "User File Count - Individual Shares - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fileshare_user_count_all{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}  -  {{Share}}"
    }
   ]
  },
  { "title": "Inactive Data ( > 6MO )", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 }, "options": { "content": "\n\n" } },
  {
   "title": " Inactive Capacity Total - All Shares",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "fileshare_user_capacity_aged{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 26, "w": 1, "x": 12, "y": 51 }, "options": { "content": "\n\n" } },
  {
   "title": "Inactive File Count Total - All Shares",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "fileshare_user_count_aged{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 60 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 1, "w": 11, "x": 13, "y": 60 }, "options": { "content": "\n\n" } },
  {
   "title": "Inactive Capacity - Individual Shares",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "fileshare_user_capacity_all_aged{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}} - {{Share}}"
    }
   ]
  },
  {
   "title": "Inactive File Count - Individual Shares",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fileshare_user_count_all_aged{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}} - {{Share}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 68 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 1, "w": 11, "x": 13, "y": 68 }, "options": { "content": "\n\n" } },
  {
   "title": "Inactive Capacity - Individual Shares - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "fileshare_user_capacity_all_aged{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}} - {{Share}}"
    }
   ]
  },
  {
   "title": "Inactive File Count - Individual Shares - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fileshare_user_count_all_aged{User=~\"$USERSELECT\"}",
     "legendFormat": "{{User}} - {{Share}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }, "options": { "content": "\n\n" } }
 ]
}