{
 "title": "Hammerspace Metadata Replication Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Link", "label": "Select Fileshare", "query": { "query": "fileshare_replication_latency" } }
  ]
 },
 "panels": [
  { "title": "Metadata Replication Dashboard", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 41, "w": 1, "x": 0, "y": 2 }, "options": { "content": "\n\n" } },
  {
   "title": "Fileshare Metadata Replication Latency - Lastest",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 22, "x": 1, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fileshare_replication_latency{Fileshare=~\"$Link\"}",
     "legendFormat": "{{Fileshare}} - {{Mode}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 41, "w": 1, "x": 23, "y": 2 }, "options": { "content": "\n\n" } },
  { "type": "text", "gridPos": { "h": 1, "w": 22, "x": 1, "y": 12 }, "options": { "content": "\n\n" } },
  {
   "title": "Fileshare Metadata Replication Latency - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 1, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "fileshare_replication_latency{Fileshare=~\"$Link\"}",
     "legendFormat": "{{Fileshare}} - {{Mode}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 22, "x": 1, "y": 22 }, "options": { "content": "\n\n" } },
  {
   "title": "Historical  Metadata Replication Bandwidth - 5 Minute Interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 1, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "fileshare_replication_bandwidth{Fileshare=~\"$Link\"}",
     "legendFormat": "{{Fileshare}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 22, "x": 1, "y": 32 }, "options": { "content": "\n\n" } },
  {
   "title": "Replication Pending Requests - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 1, "y": 33 },
   "targets": [
    {
     "expr": "fileshare_replication_pending{Fileshare=~\"$Link\"}",
     "legendFormat": "{{Fileshare}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 10, "w": 1, "x": 12, "y": 33 }, "options": { "content": "\n\n" } },
  {
   "title": "Replication Error Count - Historical View",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 13, "y": 33 },
   "targets": [
    {
     "expr": "fileshare_replication_error_count{Fileshare=~\"$Link\"}",
     "legendFormat": "{{Fileshare}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "options": { "content": "\n\n" } }
 ]
}